GET http://localhost:5000/users/ HTTP/1.1

###

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "firstName": "ash",
  "lastName": "s",
  "email": "ash@aol.com",
  "password": "12345"
}

###

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "ash@aol.com",
  "password": "12345"
}

###

GET http://localhost:5000/schools HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzaEBhb2wuY29tIiwiaWF0IjoxNTU1MjI1MDA4LCJleHAiOjE1NTUyMjg2MDgsImp0aSI6Ijc5MDQxMWEwLTVlODItMTFlOS05MjNhLWRiYTcyZDM0OGI0ZCJ9.8T31J4ZlcZo87ooH4ZCQ3RKE7CRx7thC0L0JXsWgDtQ

###
POST http://localhost:5000/schools HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzaEBhb2wuY29tIiwiaWF0IjoxNTU1MjI1MDA4LCJleHAiOjE1NTUyMjg2MDgsImp0aSI6Ijc5MDQxMWEwLTVlODItMTFlOS05MjNhLWRiYTcyZDM0OGI0ZCJ9.8T31J4ZlcZo87ooH4ZCQ3RKE7CRx7thC0L0JXsWgDtQ

{
  "name": "School4",
  "city": "Middle Earth"
}
###

PUT http://localhost:5000/schools/1 HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzaEBhb2wuY29tIiwiaWF0IjoxNTU1MjI1MDA4LCJleHAiOjE1NTUyMjg2MDgsImp0aSI6Ijc5MDQxMWEwLTVlODItMTFlOS05MjNhLWRiYTcyZDM0OGI0ZCJ9.8T31J4ZlcZo87ooH4ZCQ3RKE7CRx7thC0L0JXsWgDtQ

{
  "name": "Changed Name"
}

###

DELETE http://localhost:5000/schools/3 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzaEBhb2wuY29tIiwiaWF0IjoxNTU1MjI1MDA4LCJleHAiOjE1NTUyMjg2MDgsImp0aSI6Ijc5MDQxMWEwLTVlODItMTFlOS05MjNhLWRiYTcyZDM0OGI0ZCJ9.8T31J4ZlcZo87ooH4ZCQ3RKE7CRx7thC0L0JXsWgDtQ

###

#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZlbmthdEBhb2wuY29tIiwiaWF0IjoxNTUxOTI2OTUxLCJleHAiOjE1NTE5MzA1NTEsImp0aSI6Ijk2MzQzYzkwLTQwODMtMTFlOS04MzBhLTIxYjI1Y2JhNTM5MyJ9.gndkUhxSc_eupks143OxTsxoxk8vZvzwuf9QRFuZw6s


GET http://localhost:5000/schools/1/houses HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzaEBhb2wuY29tIiwiaWF0IjoxNTU1MjI1MDA4LCJleHAiOjE1NTUyMjg2MDgsImp0aSI6Ijc5MDQxMWEwLTVlODItMTFlOS05MjNhLWRiYTcyZDM0OGI0ZCJ9.8T31J4ZlcZo87ooH4ZCQ3RKE7CRx7thC0L0JXsWgDtQ

###

GET http://localhost:5000/schools/1/houses/1 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzaEBhb2wuY29tIiwiaWF0IjoxNTUzMTMxODkyLCJleHAiOjE1NTMxMzU0OTIsImp0aSI6IjBmMDViOGIwLTRiNzktMTFlOS04OWNhLWEzYjEzNmM2NGM2OSJ9.refNrg38gfMBXB_64-7XvZeFjB7aX0SlvwBN8lnhdqU

###

POST http://localhost:5000/schools/1/houses HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzaEBhb2wuY29tIiwiaWF0IjoxNTU1MjI1MDA4LCJleHAiOjE1NTUyMjg2MDgsImp0aSI6Ijc5MDQxMWEwLTVlODItMTFlOS05MjNhLWRiYTcyZDM0OGI0ZCJ9.8T31J4ZlcZo87ooH4ZCQ3RKE7CRx7thC0L0JXsWgDtQ
Content-Type: application/json

{
  "name": "Slytherin",
  "color": "red"
}

###

PUT http://localhost:5000/schools/1/houses/1 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzaEBhb2wuY29tIiwiaWF0IjoxNTU1MjI1MDA4LCJleHAiOjE1NTUyMjg2MDgsImp0aSI6Ijc5MDQxMWEwLTVlODItMTFlOS05MjNhLWRiYTcyZDM0OGI0ZCJ9.8T31J4ZlcZo87ooH4ZCQ3RKE7CRx7thC0L0JXsWgDtQ
Content-Type: application/json

{
  "points": 5
}

###

DELETE  http://localhost:5000/schools/1/houses/2 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzaEBhb2wuY29tIiwiaWF0IjoxNTU1MjI1MDA4LCJleHAiOjE1NTUyMjg2MDgsImp0aSI6Ijc5MDQxMWEwLTVlODItMTFlOS05MjNhLWRiYTcyZDM0OGI0ZCJ9.8T31J4ZlcZo87ooH4ZCQ3RKE7CRx7thC0L0JXsWgDtQ

###