GET http://localhost:5000/users/ HTTP/1.1

###

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "firstName": "venky",
  "lastName": "venky",
  "email": "venky@aol.com",
  "password": "12345"
}

###

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "venky@aol.com",
  "password": "12345"
}

###

GET http://localhost:5000/schools HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZlbmt5QGFvbC5jb20iLCJpYXQiOjE1NTU2ODQ0MTYsImV4cCI6MTU1NTY4ODAxNiwianRpIjoiMWQ5NDVmYTAtNjJiMC0xMWU5LTk3ODMtODkzNTYxMzc3ZTUxIn0.2Z0EullQZcXTI9My0eX6SQXymyTlKAwZ_vwwPItfC2c

###
POST http://localhost:5000/schools HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZlbmt5QGFvbC5jb20iLCJpYXQiOjE1NTU2ODQ0MTYsImV4cCI6MTU1NTY4ODAxNiwianRpIjoiMWQ5NDVmYTAtNjJiMC0xMWU5LTk3ODMtODkzNTYxMzc3ZTUxIn0.2Z0EullQZcXTI9My0eX6SQXymyTlKAwZ_vwwPItfC2c

{
  "name": "ANV  High School",
  "city": "Fairfax"
}
###


PUT http://localhost:5000/schools/12 HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZlbmt5QGFvbC5jb20iLCJpYXQiOjE1NTU2ODQ0MTYsImV4cCI6MTU1NTY4ODAxNiwianRpIjoiMWQ5NDVmYTAtNjJiMC0xMWU5LTk3ODMtODkzNTYxMzc3ZTUxIn0.2Z0EullQZcXTI9My0eX6SQXymyTlKAwZ_vwwPItfC2c

{
  "name": "12- School"
}

###

DELETE http://localhost:5000/schools/7 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZlbmt5QGFvbC5jb20iLCJpYXQiOjE1NTU2ODQ0MTYsImV4cCI6MTU1NTY4ODAxNiwianRpIjoiMWQ5NDVmYTAtNjJiMC0xMWU5LTk3ODMtODkzNTYxMzc3ZTUxIn0.2Z0EullQZcXTI9My0eX6SQXymyTlKAwZ_vwwPItfC2c

###

#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZlbmthdEBhb2wuY29tIiwiaWF0IjoxNTUxOTI2OTUxLCJleHAiOjE1NTE5MzA1NTEsImp0aSI6Ijk2MzQzYzkwLTQwODMtMTFlOS04MzBhLTIxYjI1Y2JhNTM5MyJ9.gndkUhxSc_eupks143OxTsxoxk8vZvzwuf9QRFuZw6s


GET http://localhost:5000/schools/11/houses HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZlbmt5QGFvbC5jb20iLCJpYXQiOjE1NTU2ODQ0MTYsImV4cCI6MTU1NTY4ODAxNiwianRpIjoiMWQ5NDVmYTAtNjJiMC0xMWU5LTk3ODMtODkzNTYxMzc3ZTUxIn0.2Z0EullQZcXTI9My0eX6SQXymyTlKAwZ_vwwPItfC2c

###

GET http://localhost:5000/schools/11/houses/2 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZlbmt5QGFvbC5jb20iLCJpYXQiOjE1NTU2ODQ0MTYsImV4cCI6MTU1NTY4ODAxNiwianRpIjoiMWQ5NDVmYTAtNjJiMC0xMWU5LTk3ODMtODkzNTYxMzc3ZTUxIn0.2Z0EullQZcXTI9My0eX6SQXymyTlKAwZ_vwwPItfC2c

###

POST http://localhost:5000/schools/11/houses HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZlbmt5QGFvbC5jb20iLCJpYXQiOjE1NTU2ODQ0MTYsImV4cCI6MTU1NTY4ODAxNiwianRpIjoiMWQ5NDVmYTAtNjJiMC0xMWU5LTk3ODMtODkzNTYxMzc3ZTUxIn0.2Z0EullQZcXTI9My0eX6SQXymyTlKAwZ_vwwPItfC2c
Content-Type: application/json

{
  "name": "House-3",
  "color": "Blue"
}

###

PUT http://localhost:5000/schools/1/houses/1 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZlbmt5QGFvbC5jb20iLCJpYXQiOjE1NTU2ODQ0MTYsImV4cCI6MTU1NTY4ODAxNiwianRpIjoiMWQ5NDVmYTAtNjJiMC0xMWU5LTk3ODMtODkzNTYxMzc3ZTUxIn0.2Z0EullQZcXTI9My0eX6SQXymyTlKAwZ_vwwPItfC2c
Content-Type: application/json

{
  "points": 5
}

###

DELETE  http://localhost:5000/schools/1/houses/2 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZlbmt5QGFvbC5jb20iLCJpYXQiOjE1NTU2ODQ0MTYsImV4cCI6MTU1NTY4ODAxNiwianRpIjoiMWQ5NDVmYTAtNjJiMC0xMWU5LTk3ODMtODkzNTYxMzc3ZTUxIn0.2Z0EullQZcXTI9My0eX6SQXymyTlKAwZ_vwwPItfC2c

###